### ISSUE TITLE
P "implies" Q → vs ⇒

### ISSUE THREAD

**Issue by SquidXTV** [gsayson/h3-mathematics-2025#1]
# About
In `1.3 Connectives and conditionals` it says this:
> We write this as P =⇒ Q (P “implies”Q) where P is known as the antecedent and Q is known as the consequent. (Some authors may annotate P → Q instead.)

I am not sure, but I don't think `→` is the same as `⇒`.
I remember from a different book that `P ⇒ Q` is used if `P → Q` is a tautology.

**Comment by gsayson** [comment]
You are correct; it's better to use $\to$ than $\implies$ since we're operating to make a statement, not comparing them.

I'll change to use the former, and try to avoid going too deep on the difference since this is intended as a supplementary and self-study text; most authors indeed use $\to$.

Thank you for raising the issue!

**Comment by gsayson** [comment]
I'll close the issue once I fix this.
